### PR TITLE
Replace 'lights' param with global uniform in 'traceScene'. Closes #456

### LINKED ISSUE #456: Can't see the examples.
Hello, want to check out the examples, the shader errors occur.

I wonder the reason of those errors.

Screenshot 2023-10-06 at 3 40 56 PM

**Platform:**

 - Device: M1 Mac
 - OS: Ventura 13.3.1
 - GPU: [NVidia ??, Radeon ??, ...]
 - Browser: Chrome
 - Three.js version: 0.157.0
 - Library version: 0.0.16

### PR DESCRIPTION
**Pull request by oh-jinsu**
Seems weird, but I figured out the `lights` param in `traceScene` causes the error. (I've checked the shaders are compiled well, but after `gl.linkProgram()`, the `LINK_STATUS` is false. (As I reported to the linked issue, in my device Macbook Pro 13, 2020)

In the shader, only two functions call `traceScene()`. The one in `main` function works but when calling `traceScene()` in `attenuateHit()` with the `lights` param, the error occurs. Do you have any idea why this problem happens? I'm still wondering.

It's not a fundamental solution, but I tried removing the parameter and replace it with the global uniform `lights`. Then I could see finally it's working on my device, but I wonder if using the global uniform is fine. Please let me know if you expect any problem with this commit. I'll try to find another solution. Thank you.

### CODE REVIEW

**Comment by gkjohnson** [comment]
> Do you have any idea why this problem happens? I'm still wondering.

It's a bit of a mystery - but that's consistent with other fixes for these types of opaque issues. These seem like hiccups in shader compiler but the lack of error entirely makes these frustrating to track down. Part of me is wondering if theres some problem with shaders using the same name as a global variable or passing potentially large large data structures into functions in some cases.

Either way this fixes the problem for me on Safari on my 2021 M1 Macbook Pro. For consistency maybe we should just move any global variables out of function parameters. So why don't we remove "bvh", as well, for this PR and make a comment referencing this PR #457 at the top of the "TraceScene" function so the issue is noted somewhere.

**Comment by gkjohnson** [comment]
Also possibly related to https://github.com/gkjohnson/three-gpu-pathtracer/issues/450, https://github.com/gkjohnson/three-gpu-pathtracer/issues/439

**Comment by oh-jinsu** [comment]
I moved `bvh` out of the function parameter and commented about the issue on `traceScene()`.

Thanks for your review!

**Comment by gkjohnson** [comment]
Great thanks!

I've tested a bit more and, strangely, I'm seeing that even with the fix the extremely simple "primitives.html" example still _doesn't_ work while the more complex "index.html" and "basic.html" examples do. Are you seeing this, as well? I wonder if it has anything to do with textures not being used?

**Comment by oh-jinsu** [comment]
Well, it's weird but in this time it does work on my device after moving out the global variables from the function paramters. I pulled your updated example and tested it:

Screenshot 2023-10-16 at 9 46 57 PM

**Comment by gkjohnson** [comment]
Interesting 🤔 We'll merge this and I'll look into this issue on my machine.

Thanks again for your work on this!

**Pull request merged**
